language: java

jdk:
 - openjdk8
 - openjdk11

cache:
 directories:
  - $HOME/.m2

before_cache:
 - rm -rf $HOME/.m2/repository/com/github/jamesnetherton

before_script:
 - ./mvnw process-sources -P licenseCheck

script:
 - ./mvnw clean install -P examples

deploy:
  provider: script
  script: bash docker-build.sh
  on:
    tags: true
