language: java

jdk:
 - openjdk8
 - openjdk11

before_script:
 - ./mvnw process-sources -P licenseCheck

script:
 - ./mvnw clean install

deploy:
  provider: script
  script: bash docker-build.sh
  on:
    tags: true
