language: java

jdk:
 - openjdk8
 - openjdk11
 - openjdk14

cache:
 directories:
  - $HOME/.m2

before_cache:
 - rm -rf $HOME/.m2/repository/com/github/jamesnetherton

before_script:
 - ./mvnw process-sources -ntp -B -P licenseCheck

script:
 - ./mvnw clean install -ntp -B -P examples -P galleon-provision
 - ./mvnw clean install -ntp -B -P distro-provision

deploy:
  provider: script
  script: bash docker-build.sh
  on:
    tags: true
